---
- name: Create a new Demo EC2 instance
  hosts: ec2
  gather_facts: False

  vars:
      region: us-east-1
      instance_type: t2.nano
      ami:  ami-04b9e92b5572fa0d1  # Ubuntu 16.04 LTS
      keypair: NVirginia.pem # pem file name
  
  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: Lucky_SG  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         vpc_subnet_id: subnet-0a536236370d5c0b4
         assign_public_ip: yes
      register: ec2
